#!/bin/sh

# Check if required variables are set
true "${KAS_DB_USER:?ERROR! KAS_DB_USER is unset.}"
true "${KAS_DB:?ERROR! KAS_DB_NAME is unset.}"
true "${KAS_DB_PASSWORD:?ERROR! KAS_DB_PASSWORD is unset.}"

true "${SELVBETJENING_DB_USER:?ERROR! SELVBETJENING_DB_USER is unset.}"
true "${SELVBETJENING_DB:?ERROR! SELVBETJENING_DB_NAME is unset.}"
true "${SELVBETJENING_DB_PASSWORD:?ERROR! SELVBETJENING_DB_PASSWORD is unset.}"

# Intentionally not indented due to the way psql parses the statements.
psql -v ON_ERROR_STOP=1 <<-EOSQL
        CREATE DATABASE ${KAS_DB};
        CREATE USER ${KAS_DB_USER} WITH ENCRYPTED PASSWORD '${KAS_DB_PASSWORD}';
        GRANT ALL PRIVILEGES ON DATABASE ${KAS_DB} TO ${KAS_DB_USER};
        ALTER USER ${KAS_DB_USER} CREATEDB;
        CREATE DATABASE ${SELVBETJENING_DB};
        CREATE USER ${SELVBETJENING_DB_USER} WITH ENCRYPTED PASSWORD '${SELVBETJENING_DB_PASSWORD}';
        GRANT ALL PRIVILEGES ON DATABASE ${SELVBETJENING_DB} TO ${SELVBETJENING_DB_USER};
        ALTER USER ${SELVBETJENING_DB_USER} CREATEDB;
EOSQL
