# Generated by Django 2.2.18 on 2021-04-19 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kas', '0006_auto_20210412_1341'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('status', models.TextField(blank=True, choices=[('created', 'Oprettet'), ('ready', 'Klar til overførsel'), ('transferred', 'Overført')], default='created')),
                ('type', models.TextField(choices=[('charge', 'opkrævning'), ('repayment', 'tilbagebetaling'), ('adjustment', 'justering')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('person_tax_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kas.PersonTaxYear')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfered_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
