# Generated by Django 2.2.18 on 2021-05-17 08:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import prisme.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prisme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
        migrations.AddField(
            model_name='transaction',
            name='object_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.TextField(choices=[('charge', 'opkrævning'), ('repayment', 'tilbagebetaling'), ('adjustment', 'justering'), ('prepayment', 'Forudindbetaling')]),
        ),
        migrations.CreateModel(
            name='PrePaymentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=prisme.models.payment_file_by_year, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
