# Generated by Django 2.2.18 on 2021-07-16 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kas', '0015_finalsettlement_invalid'),
        ('prisme', '0003_auto_20210527_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created_at', 'uuid'], 'verbose_name': 'transaktion', 'verbose_name_plural': 'transaktionr'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transferred_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transferred_by',
        ),
        migrations.AddField(
            model_name='transaction',
            name='prisme10Q_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.TextField(blank=True, choices=[('created', 'Oprettet'), ('ready', 'Klar til overførsel'), ('transferred', 'Overført'), ('cancelled', 'Annuleret')], default='created'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.TextField(choices=[('prisme10q', 'Prisme opkrævning / tilbagebetaling'), ('prepayment', 'Forudindbetaling')]),
        ),
        migrations.CreateModel(
            name='Prisme10QBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('delivered', models.DateTimeField(blank=True, null=True)),
                ('delivery_error', models.TextField(blank=True, default='')),
                ('status', models.IntegerField(choices=[(1, 'Ikke afsendt'), (2, 'Afsendelse fejlet'), (3, 'Afsendt')], default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_prisme_batches', to=settings.AUTH_USER_MODEL)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_prisme_batches', to=settings.AUTH_USER_MODEL)),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kas.TaxYear')),
            ],
            options={
                'verbose_name': 'prisme 10Q batch',
                'verbose_name_plural': 'prisme 10Q batches',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='prisme10Q_batch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='prisme.Prisme10QBatch'),
        ),
    ]
