# Generated by Django 2.2.18 on 2021-07-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisme', '0004_auto_20210716_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisme10qbatch',
            name='ref_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
