# Generated by Django 2.2.18 on 2021-09-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisme', '0005_auto_20210806_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created_at', 'uuid'], 'verbose_name': 'transaktion', 'verbose_name_plural': 'transaktioner'},
        ),
    ]
