# Generated by Django 2.2.18 on 2021-08-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisme', '0005_prisme10qbatch_ref_timestamp'),
        ('prisme', '0006_auto_20210805_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prisme10qbatch',
            old_name='ref_timestamp',
            new_name='collect_date',
        ),
    ]
