# Generated by Django 2.2.18 on 2021-08-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisme', '0005_auto_20210803_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisme10qbatch',
            name='status',
            field=models.CharField(choices=[('created', 'Ikke afsendt'), ('failed', 'Afsendelse fejlet'), ('delivered', 'Afsendt'), ('cancelled', 'Annulleret')], default='created', max_length=15),
        ),
    ]
