# Generated by Django 2.2.26 on 2022-02-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisme', '0006_auto_20210917_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisme10qbatch',
            name='collect_date',
            field=models.DateField(null=True),
        ),
    ]
