# Generated by Django 2.2.26 on 2022-03-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisme', '0007_auto_20220221_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.TextField(blank=True, choices=[('created', 'Oprettet'), ('ready', 'Klar til overførsel'), ('transferred', 'Overført'), ('cancelled', 'Annulleret'), ('indifferent', 'Afregnes ikke')], default='created'),
        ),
    ]
