# Generated by Django 3.2.12 on 2023-01-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisme', '0009_alter_prepaymentfile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepaymentfile',
            options={'ordering': ['uploaded_at']},
        ),
    ]
