# Generated by Django 3.2.12 on 2023-01-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisme', '0010_alter_prepaymentfile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='prisme10Q_batch',
            new_name='prisme10q_batch',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='prisme10Q_content',
            new_name='prisme10q_content',
        ),
    ]
