# Generated by Django 3.2.12 on 2023-01-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisme', '0011_auto_20230105_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prisme10qbatch',
            options={'ordering': ['-created'], 'verbose_name': 'prisme 10Q batch', 'verbose_name_plural': 'prisme 10Q batches'},
        ),
    ]
