# Generated by Django 2.2.18 on 2021-02-16 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(db_index=True, help_text='Antal dage', verbose_name='Antal dage')),
            ],
        ),
        migrations.CreateModel(
            name='PensionCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, help_text='Navn', verbose_name='Navn')),
                ('address', models.TextField(help_text='Adresse', verbose_name='Adresse')),
                ('email', models.TextField(help_text='E-mail', verbose_name='E-mail')),
                ('phone', models.TextField(help_text='Telefon', verbose_name='Telefon')),
                ('cvr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpr', models.TextField(db_index=True, help_text='CPR nummer', verbose_name='CPR nummer')),
            ],
        ),
        migrations.CreateModel(
            name='PersonTaxYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Startdato')),
                ('end_date', models.DateField(verbose_name='Slutdato')),
                ('number_of_days', models.IntegerField(verbose_name='Antal dage')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kas.Person')),
            ],
        ),
        migrations.CreateModel(
            name='TaxYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='Skatteår', verbose_name='Skatteår')),
            ],
        ),
        migrations.CreateModel(
            name='R75',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preprinted_net_return', models.BigIntegerField(default=0, verbose_name='Fortrykt nettoafkast')),
                ('person_tax_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kas.PersonTaxYear')),
            ],
        ),
        migrations.CreateModel(
            name='PriorYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_paid_in_prior_years', models.BigIntegerField(db_index=True, help_text='Skat betalt i tidligere år', verbose_name='Skat betalt i tidligere år')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kas.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyTaxYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=40)),
                ('prefilled_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Beløb rapporteret fra forsikringsselskab')),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Skønsbeløb angivet af Skattestyrelsen')),
                ('self_reported_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Selvangivet beløb')),
                ('active_amount', models.SmallIntegerField(choices=[(1, 'Beløb rapporteret fra forsikringsselskab'), (2, 'Skønsbeløb angivet af Skattestyrelsen'), (3, 'Selvangivet beløb')], default=1, verbose_name='Beløb brugt til beregning')),
                ('calculation_model', models.SmallIntegerField(choices=[(1, 'Standard'), (2, 'Alternativ')], default=1, verbose_name='Beregningsmodel')),
                ('preliminary_paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Foreløbigt betalt kapitalafkast')),
                ('from_pension', models.BooleanField(default=False, verbose_name='Er kapitalafkastskatten hævet fra pensionsordning')),
                ('foreign_paid_amount_self_reported', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Selvangivet beløb for betalt kapitalafkastskat i udlandet')),
                ('foreign_paid_amount_actual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Faktisk betalt kapitalafkastskat i udlandet')),
                ('deduction_from_previous_years', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Fradrag fra tidligere år')),
                ('applied_deduction_from_previous_years', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Anvendt fradrag fra tidligere år')),
                ('calculated_result', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Beregnet resultat')),
                ('modified_by', models.CharField(max_length=255, verbose_name='Modificeret af')),
                ('locked', models.BooleanField(default=False, help_text='Låst', verbose_name='Låst')),
                ('note', models.TextField(verbose_name='Note')),
                ('pension_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kas.PensionCompany')),
                ('person_tax_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kas.PersonTaxYear')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Navn')),
                ('description', models.TextField(verbose_name='Beskrivelse')),
                ('file', models.FileField(upload_to='', verbose_name='Fil')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kas.PolicyTaxYear')),
            ],
        ),
        migrations.AddField(
            model_name='persontaxyear',
            name='tax_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kas.TaxYear'),
        ),
    ]
