# Generated by Django 2.2.18 on 2021-04-07 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(verbose_name='Tekst')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('person_tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='kas.PersonTaxYear')),
                ('policy_tax_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='kas.PolicyTaxYear')),
            ],
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='historicalpolicytaxyear',
            name='note',
        ),
        migrations.RemoveField(
            model_name='policytaxyear',
            name='note',
        ),
    ]
