# Generated by Django 2.2.18 on 2021-02-18 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0002_41305_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytaxyear',
            name='applied_deduction_from_previous_years',
            field=models.BigIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Anvendt fradrag fra tidligere år'),
        ),
        migrations.AlterField(
            model_name='policytaxyear',
            name='calculated_result',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Beregnet resultat'),
        ),
        migrations.AlterField(
            model_name='policytaxyear',
            name='deduction_from_previous_years',
            field=models.BigIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Fradrag fra tidligere år'),
        ),
        migrations.AlterField(
            model_name='policytaxyear',
            name='estimated_amount',
            field=models.BigIntegerField(default=0, verbose_name='Skønsbeløb angivet af Skattestyrelsen'),
        ),
        migrations.AlterField(
            model_name='policytaxyear',
            name='foreign_paid_amount_actual',
            field=models.BigIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Faktisk betalt kapitalafkastskat i udlandet'),
        ),
        migrations.AlterField(
            model_name='policytaxyear',
            name='foreign_paid_amount_self_reported',
            field=models.BigIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Selvangivet beløb for betalt kapitalafkastskat i udlandet'),
        ),
        migrations.AlterField(
            model_name='policytaxyear',
            name='prefilled_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Beløb rapporteret fra forsikringsselskab'),
        ),
        migrations.AlterField(
            model_name='policytaxyear',
            name='preliminary_paid_amount',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Foreløbigt betalt kapitalafkast'),
        ),
        migrations.AlterField(
            model_name='policytaxyear',
            name='self_reported_amount',
            field=models.BigIntegerField(null=True, verbose_name='Selvangivet beløb'),
        ),
    ]
