# Generated by Django 2.2.18 on 2021-02-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0002_41305_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beskrivelse'),
        ),
    ]
