# Generated by Django 2.2.18 on 2021-03-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0003_decimalfield_to_bigintegerfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policytaxyear',
            name='deduction_from_previous_years',
        ),
        migrations.AddField(
            model_name='policytaxyear',
            name='calculated_full_tax',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Beregnet skat uden fradrag'),
        ),
        migrations.AddField(
            model_name='policytaxyear',
            name='year_adjusted_amount',
            field=models.BigIntegerField(default=0, verbose_name='Beløb justeret for dage i skatteår'),
        ),
    ]
