# Generated by Django 2.2.18 on 2021-03-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0003_decimalfield_to_bigintegerfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persontaxyear',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='persontaxyear',
            name='start_date',
        ),
        migrations.AddField(
            model_name='persontaxyear',
            name='fully_tax_liable',
            field=models.BooleanField(default=True, verbose_name='Fuldt skattepligtig'),
        ),
        migrations.AddField(
            model_name='person',
            name='address_line_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='address_line_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='address_line_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='address_line_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='address_line_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='municipality_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='municipality_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
