# Generated by Django 2.2.18 on 2021-02-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0003_decimalfield_to_bigintegerfield'),
        ('kas', '0003_auto_20210218_1244'),
    ]

    operations = [
    ]
