# Generated by Django 2.2.18 on 2021-04-12 11:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kas', '0003_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydocument',
            name='person_tax_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kas.PersonTaxYear'),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 12, 11, 29, 8, 683285, tzinfo=timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policydocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policydocument',
            name='policy_tax_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_documents', to='kas.PolicyTaxYear'),
        ),
    ]
