# Generated by Django 2.2.18 on 2021-04-12 11:30

from django.db import migrations


def set_person(apps, schema_editor):
    PolicyDocument = apps.get_model('kas', 'PolicyDocument')

    for document in PolicyDocument.objects.all():
        document.person_tax_year = document.policy_tax_year.person_tax_year
        document.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0004_auto_20210412_1329'),
    ]

    operations = [
        migrations.RunPython(set_person, noop),
    ]
