# Generated by Django 2.2.18 on 2021-03-08 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0006_merge_20210307_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousYearNegativePayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_negative_payout', models.BigIntegerField(blank=True, default=0, verbose_name='Overført negativt afkast')),
                ('used_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_for', to='kas.PolicyTaxYear')),
                ('used_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_from', to='kas.PolicyTaxYear')),
            ],
        ),
    ]
