# Generated by Django 2.2.18 on 2021-03-08 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0005_40973_person_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousYearNegativePayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_negative_payout', models.BigIntegerField(blank=True, default=0, verbose_name='Overført negativt afkast')),
                ('used_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kas.PolicyTaxYear')),
            ],
        ),
    ]
