# Generated by Django 2.2.18 on 2021-04-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0005_setPerson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydocument',
            name='person_tax_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kas.PersonTaxYear'),
        ),
    ]
