# Generated by Django 2.2.18 on 2021-03-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0005_41973_person_history'),
        ('kas', '0004_auto_20210302_1349'),
    ]

    operations = [
    ]
