# Generated by Django 2.2.18 on 2021-04-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0006_auto_20210412_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persontaxyear',
            options={'ordering': ['-tax_year__year', 'person__name']},
        ),
        migrations.AlterModelOptions(
            name='taxyear',
            options={'ordering': ['-year']},
        ),
    ]
