# Generated by Django 2.2.18 on 2021-04-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0007_pensioncompanysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicytaxyear',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='policytaxyear',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
