# Generated by Django 2.2.18 on 2021-04-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0006_auto_20210412_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persontaxyear',
            options={'ordering': ['-tax_year__year', 'person__name']},
        ),
        migrations.AlterModelOptions(
            name='taxyear',
            options={'ordering': ['-year']},
        ),
        migrations.RemoveField(
            model_name='historicalpolicytaxyear',
            name='estimated_amount',
        ),
        migrations.RemoveField(
            model_name='policytaxyear',
            name='estimated_amount',
        ),
        migrations.AddField(
            model_name='historicalpolicytaxyear',
            name='adjusted_r75_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Justeret R75 beløb'),
        ),
        migrations.AddField(
            model_name='historicalpolicytaxyear',
            name='assessed_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Ansat beløb'),
        ),
        migrations.AddField(
            model_name='policytaxyear',
            name='adjusted_r75_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Justeret R75 beløb'),
        ),
        migrations.AddField(
            model_name='policytaxyear',
            name='assessed_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Ansat beløb'),
        ),
        migrations.AlterField(
            model_name='historicalpolicytaxyear',
            name='active_amount',
            field=models.SmallIntegerField(choices=[(1, 'Beløb rapporteret fra pensionsselskab'), (3, 'Selvangivet beløb')], default=1, verbose_name='Beløb brugt til beregning'),
        ),
        migrations.AlterField(
            model_name='policytaxyear',
            name='active_amount',
            field=models.SmallIntegerField(choices=[(1, 'Beløb rapporteret fra pensionsselskab'), (3, 'Selvangivet beløb')], default=1, verbose_name='Beløb brugt til beregning'),
        ),
    ]
