# Generated by Django 2.2.18 on 2021-03-11 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0006_previousyearnegativepayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSlipGenerated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FilePathField(null=True, path='/srv/')),
                ('status', models.SmallIntegerField(choices=[(1, 'created'), (2, 'pending'), (3, 'sent_to_proxy'), (4, 'delivered_to_eboks'), (5, 'delivered_to_snailmail'), (6, 'failed')], default=1, verbose_name='created')),
            ],
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='previousyearnegativepayout',
            name='used_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payouts_used', to='kas.PolicyTaxYear'),
        ),
        migrations.AlterField(
            model_name='previousyearnegativepayout',
            name='used_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payouts_using', to='kas.PolicyTaxYear'),
        ),
        migrations.AddField(
            model_name='policytaxyear',
            name='tax_slip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kas.TaxSlipGenerated'),
        ),
    ]
