# Generated by Django 2.2.18 on 2021-04-21 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kas.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kas', '0006_auto_20210412_1341'),
        ('kas', '0007_auto_20210427_1651')
    ]

    operations = [
        migrations.CreateModel(
            name='PensionCompanySummaryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=kas.models.pensioncompanysummaryfile_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kas.PensionCompany')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kas.TaxYear')),
            ],
        ),
        migrations.CreateModel(
            name='PensionCompanySummaryFileDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_to', models.GenericIPAddressField(null=True)),
                ('downloaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kas.PensionCompanySummaryFile')),
            ],
        ),
        migrations.AddField(
            model_name='historicalpolicytaxyear',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='policytaxyear',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
