# Generated by Django 2.2.18 on 2021-03-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0007_auto_20210310_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicytaxyear',
            name='available_negative_return',
            field=models.BigIntegerField(blank=True, default=None, editable=False, null=True, verbose_name='Tilgængeligt fradrag fra andre år (beregnet ud fra andre data)'),
        ),
        migrations.AddField(
            model_name='policytaxyear',
            name='available_negative_return',
            field=models.BigIntegerField(blank=True, default=None, editable=False, null=True, verbose_name='Tilgængeligt fradrag fra andre år (beregnet ud fra andre data)'),
        ),
    ]
