# Generated by Django 2.2.18 on 2021-03-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0007_auto_20210311_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policytaxyear',
            name='tax_slip',
        ),
        migrations.AddField(
            model_name='historicalpersontaxyear',
            name='tax_slip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kas.TaxSlipGenerated'),
        ),
        migrations.AddField(
            model_name='persontaxyear',
            name='tax_slip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kas.TaxSlipGenerated'),
        ),
        migrations.AddField(
            model_name='taxslipgenerated',
            name='message_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='taxslipgenerated',
            name='post_processing_status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='taxslipgenerated',
            name='recipient_status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='taxslipgenerated',
            name='file',
            field=models.FileField(null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='taxslipgenerated',
            name='status',
            field=models.TextField(blank=True, choices=[('created', 'KAS Selvangivelse genereret'), ('sent', 'KAS Selvangivelse afsendt'), ('post_processing', 'Afventer efterbehandling'), ('failed', 'Afsendelse fejlet')], default='created'),
        ),
    ]
