# Generated by Django 2.2.18 on 2021-03-11 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0008_auto_20210311_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensioncompany',
            name='cvr',
        ),
        migrations.RemoveField(
            model_name='pensioncompany',
            name='reg_nr',
        ),
        migrations.AddField(
            model_name='pensioncompany',
            name='accepts_payments',
            field=models.BooleanField(default=False, verbose_name='Modtager indbetalinger'),
        ),
        migrations.AddField(
            model_name='pensioncompany',
            name='domestic_or_foreign',
            field=models.IntegerField(choices=[(0, 'Uvist'), (1, 'Indenlandsk'), (2, 'Udenlandsk')], default=0),
        ),
        migrations.AddField(
            model_name='pensioncompany',
            name='res',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Identificerende nummer (reg.nr. for banker, se-nr for pensionsselskaber)'),
        ),
    ]
