# Generated by Django 2.2.18 on 2021-03-15 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0009_auto_20210311_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSlipGenerated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='reports/')),
                ('status', models.TextField(blank=True, choices=[('created', 'KAS Selvangivelse genereret'), ('sent', 'KAS Selvangivelse afsendt'), ('post_processing', 'Afventer efterbehandling'), ('failed', 'Afsendelse fejlet')], default='created')),
                ('post_processing_status', models.TextField(blank=True, default='')),
                ('recipient_status', models.TextField(blank=True, default='')),
                ('message_id', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpersontaxyear',
            name='tax_slip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kas.TaxSlipGenerated'),
        ),
        migrations.AddField(
            model_name='persontaxyear',
            name='tax_slip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kas.TaxSlipGenerated'),
        ),
    ]
