# Generated by Django 2.2.18 on 2021-05-19 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import kas.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0009_auto_20210518_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxslipgenerated',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 19, 10, 9, 35, 237138, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxslipgenerated',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxslipgenerated',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxslipgenerated',
            name='post_processing_status',
            field=models.TextField(blank=True, choices=[('pending', 'Afventer processering'), ('address resolved', 'Fundet gyldig postadresse'), ('address not found', 'Ingen gyldig postadresse'), ('remote printed', 'Overført til fjernprint')], default=''),
        ),
        migrations.AlterField(
            model_name='taxslipgenerated',
            name='recipient_status',
            field=models.TextField(blank=True, choices=[('', 'Gyldig E-boks modtager'), ('exempt', 'Fritaget modtager'), ('invalid', 'Ugyldig E-boks modtager (sendes til efterbehandling)'), ('dead', 'Afdød'), ('minor', 'Mindreårig')], default=''),
        ),
        migrations.AlterField(
            model_name='taxslipgenerated',
            name='status',
            field=models.TextField(blank=True, choices=[('created', 'Genereret'), ('send', 'Afsendt'), ('post_processing', 'Afventer efterbehandling'), ('failed', 'Afsendelse fejlet')], default='created'),
        ),
        migrations.CreateModel(
            name='FinalSettlement',
            fields=[
                ('title', models.TextField()),
                ('status', models.TextField(blank=True, choices=[('created', 'Genereret'), ('send', 'Afsendt'), ('post_processing', 'Afventer efterbehandling'), ('failed', 'Afsendelse fejlet')], default='created')),
                ('post_processing_status', models.TextField(blank=True, choices=[('pending', 'Afventer processering'), ('address resolved', 'Fundet gyldig postadresse'), ('address not found', 'Ingen gyldig postadresse'), ('remote printed', 'Overført til fjernprint')], default='')),
                ('recipient_status', models.TextField(blank=True, choices=[('', 'Gyldig E-boks modtager'), ('exempt', 'Fritaget modtager'), ('invalid', 'Ugyldig E-boks modtager (sendes til efterbehandling)'), ('dead', 'Afdød'), ('minor', 'Mindreårig')], default='')),
                ('message_id', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pdf', models.FileField(upload_to=kas.models.final_settlement_file_path)),
                ('person_tax_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kas.PersonTaxYear')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
