# Generated by Django 2.2.18 on 2021-03-17 11:05

from django.db import migrations, models
import kas.models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0010_auto_20210315_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxslipgenerated',
            name='file',
            field=models.FileField(null=True, upload_to=kas.models.taxslip_path_by_year),
        ),
    ]
