# Generated by Django 2.2.18 on 2021-03-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0010_auto_20210315_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpolicytaxyear',
            name='active_amount',
            field=models.SmallIntegerField(choices=[(1, 'Beløb rapporteret fra pensionsselskab'), (2, 'Skønsbeløb angivet af Skattestyrelsen'), (3, 'Selvangivet beløb')], default=1, verbose_name='Beløb brugt til beregning'),
        ),
        migrations.AlterField(
            model_name='historicalpolicytaxyear',
            name='prefilled_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Beløb rapporteret fra pensionsselskab'),
        ),
        migrations.AlterField(
            model_name='policytaxyear',
            name='active_amount',
            field=models.SmallIntegerField(choices=[(1, 'Beløb rapporteret fra pensionsselskab'), (2, 'Skønsbeløb angivet af Skattestyrelsen'), (3, 'Selvangivet beløb')], default=1, verbose_name='Beløb brugt til beregning'),
        ),
        migrations.AlterField(
            model_name='policytaxyear',
            name='prefilled_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Beløb rapporteret fra pensionsselskab'),
        ),
    ]
