# Generated by Django 2.2.18 on 2021-03-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0011_auto_20210317_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpolicytaxyear',
            name='active_amount',
            field=models.SmallIntegerField(choices=[(1, 'Beløb rapporteret fra pensionsselskab'), (2, 'Skønsbeløb angivet af Skattestyrelsen'), (3, 'Selvangivet beløb')], default=1, verbose_name='Beløb brugt til beregning'),
        ),
        migrations.AlterField(
            model_name='historicalpolicytaxyear',
            name='prefilled_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Beløb rapporteret fra pensionsselskab'),
        ),
        migrations.AlterField(
            model_name='policytaxyear',
            name='active_amount',
            field=models.SmallIntegerField(choices=[(1, 'Beløb rapporteret fra pensionsselskab'), (2, 'Skønsbeløb angivet af Skattestyrelsen'), (3, 'Selvangivet beløb')], default=1, verbose_name='Beløb brugt til beregning'),
        ),
        migrations.AlterField(
            model_name='policytaxyear',
            name='prefilled_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Beløb rapporteret fra pensionsselskab'),
        ),
    ]
