# Generated by Django 2.2.18 on 2021-05-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0012_fix_policy_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicytaxyear',
            name='next_processing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Næste behandlingsdato'),
        ),
        migrations.AddField(
            model_name='policytaxyear',
            name='next_processing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Næste behandlingsdato'),
        ),
        migrations.AlterField(
            model_name='historicalpolicytaxyear',
            name='self_reported_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Selvangivet beløb'),
        ),
        migrations.AlterField(
            model_name='policytaxyear',
            name='self_reported_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Selvangivet beløb'),
        ),
        migrations.AlterField(
            model_name='taxyear',
            name='year_part',
            field=models.TextField(choices=[('selvangivelse', 'Selvangivelsesperiode'), ('ligning', 'Ligningsperiode'), ('genoptagelsesperiode', 'Genoptagelsesperiode')], default='selvangivelse'),
        ),
    ]
