# Generated by Django 2.2.18 on 2021-03-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0012_auto_20210317_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersontaxyear',
            name='foreign_pension_notes',
            field=models.TextField(null=True, verbose_name='Noter om pension i udlandet'),
        ),
        migrations.AddField(
            model_name='historicalpersontaxyear',
            name='general_notes',
            field=models.TextField(null=True, verbose_name='Yderligere noter'),
        ),
        migrations.AddField(
            model_name='historicalpolicytaxyear',
            name='self_reported_used_deduction',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Borgerønsket fradrag fra andre år'),
        ),
        migrations.AddField(
            model_name='persontaxyear',
            name='foreign_pension_notes',
            field=models.TextField(null=True, verbose_name='Noter om pension i udlandet'),
        ),
        migrations.AddField(
            model_name='persontaxyear',
            name='general_notes',
            field=models.TextField(null=True, verbose_name='Yderligere noter'),
        ),
        migrations.AddField(
            model_name='policytaxyear',
            name='self_reported_used_deduction',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Borgerønsket fradrag fra andre år'),
        ),
    ]
