# Generated by Django 2.2.18 on 2021-05-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0012_fix_policy_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxyear',
            name='year_part',
            field=models.TextField(choices=[('selvangivelse', 'Selvangivelsesperiode'), ('ligning', 'Ligningsperiode'), ('genoptagelsesperiode', 'Genoptagelsesperiode')], default='selvangivelse'),
        ),
    ]
