# Generated by Django 2.2.18 on 2021-05-21 08:32

from django.db import migrations


def forward(apps, schema_editor):
    PolicyTaxYear = apps.get_model("kas", "PolicyTaxYear")

    qs = PolicyTaxYear.objects.filter(person_tax_year__tax_year=2020)

    changed = 0

    for x in qs:
        if x.assessed_amount != x.get_assessed_amount():
            changed = changed + 1
            x.assessed_amount = x.get_assessed_amount()
            x.recalculate()
            x._change_reason = "Recalculate assessed amount"
            x.save()

    print(
        "Updated assessed amount / used negative amount for %d PolixyTaxYears" % changed
    )


def revert(apps, schema_editor):
    # We cannot revert this as we will no longer have the original data
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("kas", "0013_auto_20210527_1230_squashed_0016_auto_20210608_0838"),
    ]

    operations = [
        migrations.RunPython(forward, revert),
    ]
