# Generated by Django 2.2.18 on 2021-03-23 10:26

from django.db import migrations, models
import django.db.models.deletion
import kas.models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0013_auto_20210318_0942'),
        ('kas', '0014_auto_20210322_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTaxYearCensus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_kas_mandtal', models.UUIDField()),
                ('number_of_days', models.IntegerField(null=True, verbose_name='Antal dage')),
                ('fully_tax_liable', models.BooleanField(default=True, verbose_name='Fuldt skattepligtig')),
                ('person_tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kas.PersonTaxYear')),
            ],
            bases=(kas.models.HistoryMixin, models.Model),
        ),
    ]
