# Generated by Django 2.2.18 on 2021-03-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0013_auto_20210318_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpolicytaxyear',
            name='self_reported_used_deduction',
        ),
        migrations.RemoveField(
            model_name='policytaxyear',
            name='self_reported_used_deduction',
        ),
    ]
