# Generated by Django 2.2.18 on 2021-05-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0013_auto_20210526_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpolicytaxyear',
            name='self_reported_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Selvangivet beløb'),
        ),
        migrations.AlterField(
            model_name='policytaxyear',
            name='self_reported_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Selvangivet beløb'),
        ),
    ]
