# Generated by Django 2.2.18 on 2021-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0013_auto_20210527_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersontaxyear',
            name='all_documents_and_notes_handled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='persontaxyear',
            name='all_documents_and_notes_handled',
            field=models.BooleanField(default=True),
        ),
    ]
