# Generated by Django 2.2.18 on 2021-03-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0014_auto_20210322_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensioncompany',
            name='accepts_payments',
        ),
        migrations.RemoveField(
            model_name='pensioncompany',
            name='domestic_or_foreign',
        ),
    ]
