# Generated by Django 2.2.18 on 2021-06-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0015_all_documents_and_notes_handled'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicytaxyear',
            name='citizen_pay_override',
            field=models.BooleanField(default=False, verbose_name='Borgeren betaler selvom der foreligger aftale med pensionsselskab'),
        ),
        migrations.AddField(
            model_name='policytaxyear',
            name='citizen_pay_override',
            field=models.BooleanField(default=False, verbose_name='Borgeren betaler selvom der foreligger aftale med pensionsselskab'),
        ),
    ]
