# Generated by Django 2.2.18 on 2021-03-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0015_auto_20210323_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pensioncompany',
            options={'ordering': ['name'], 'verbose_name': 'pensionsselskab', 'verbose_name_plural': 'pensionsselskaber'},
        ),
    ]
