# Generated by Django 2.2.18 on 2021-11-23 13:03

from django.db import migrations, models
import kas.models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0017_auto_20211109_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxyear',
            name='rate_text_for_transactions',
            field=models.TextField(default='', validators=[kas.models.max_sixty_characters_per_line_validator], verbose_name='Tekst brugt i opkrævninger sendt ud for skatteåret'),
        ),
    ]
