# Generated by Django 2.2.26 on 2022-01-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0020_auto_20220120_1034'),
        ('kas', '0021_auto_20220124_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersontaxyear',
            name='updated_from_dafo',
            field=models.BooleanField(default=False, verbose_name='Opdateret fra datafordeleren'),
        ),
        migrations.AddField(
            model_name='persontaxyear',
            name='updated_from_dafo',
            field=models.BooleanField(default=False, verbose_name='Opdateret fra datafordeleren'),
        ),
    ]
