# Generated by Django 2.2.26 on 2022-02-09 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kas', '0021_auto_20220126_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersontaxyear',
            name='updated_by',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalpolicytaxyear',
            name='updated_by',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='persontaxyear',
            name='updated_by',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='policytaxyear',
            name='updated_by',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='RepresentationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('consumed', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kas.Person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
