# Generated by Django 2.2.26 on 2022-03-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kas", "0028_migrate_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxyear",
            name="year_part",
            field=models.TextField(
                choices=[
                    ("selvangivelse", "Selvangivelsesperiode"),
                    ("ligning", "Ligningsperiode"),
                    ("genoptagelsesperiode", "Genoptagelsesperiode"),
                ],
                default="selvangivelse",
                verbose_name="Periode",
            ),
        ),
    ]
