# Generated by Django 3.2.12 on 2022-05-02 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0031_migrate_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_from', models.DateTimeField()),
                ('interval_to', models.DateTimeField(blank=True, null=True)),
                ('taxyear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kas.taxyear')),
            ],
            options={
                'ordering': ('interval_from',),
            },
        ),
        migrations.AddField(
            model_name='finalsettlement',
            name='lock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kas.lock'),
        ),
    ]
