# Generated by Django 3.2.12 on 2022-06-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kas", "0034_locks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalsettlement",
            name="lock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="settlements",
                to="kas.lock",
            ),
        ),
    ]
