# Generated by Django 3.2.12 on 2022-08-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0037_auto_20220628_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpolicytaxyear',
            name='policy_number',
            field=models.CharField(max_length=40, verbose_name='Policenummer'),
        ),
        migrations.AlterField(
            model_name='policytaxyear',
            name='policy_number',
            field=models.CharField(max_length=40, verbose_name='Policenummer'),
        ),
    ]
