# Generated by Django 3.2.12 on 2022-06-13 08:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kas", "0040_auto_20220926_1245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalsettlement",
            name="pseudo_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=5
            ),
        ),
    ]
