# Generated by Django 3.2.12 on 2022-10-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0042_auto_20221003_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalsettlement',
            name='pseudo_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
