# Generated by Django 3.2.12 on 2022-10-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0044_finalsettlement_indifference_limited'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicytaxyear',
            name='indifference_limited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policytaxyear',
            name='indifference_limited',
            field=models.BooleanField(default=False),
        ),
    ]
