# Generated by Django 3.2.12 on 2023-01-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0047_auto_20221107_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressfromdafo',
            options={'ordering': ['cpr']},
        ),
        migrations.AlterModelOptions(
            name='agterskrivelse',
            options={'ordering': ['person_tax_year']},
        ),
        migrations.AlterModelOptions(
            name='finalsettlement',
            options={'ordering': ['person_tax_year']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['days']},
        ),
        migrations.AlterModelOptions(
            name='pensioncompanysummaryfile',
            options={'ordering': ['company', 'tax_year']},
        ),
        migrations.AlterModelOptions(
            name='pensioncompanysummaryfiledownload',
            options={'ordering': ['downloaded_at']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['cpr']},
        ),
        migrations.AlterModelOptions(
            name='persontaxyearcensus',
            options={'ordering': ['person_tax_year']},
        ),
        migrations.AlterModelOptions(
            name='policydocument',
            options={'ordering': ['person_tax_year', 'uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='policytaxyear',
            options={'ordering': ['person_tax_year']},
        ),
        migrations.AlterModelOptions(
            name='previousyearnegativepayout',
            options={'ordering': ['used_from']},
        ),
        migrations.AlterModelOptions(
            name='prioryear',
            options={'ordering': ['person']},
        ),
        migrations.AlterModelOptions(
            name='r75',
            options={'ordering': ['person_tax_year']},
        ),
        migrations.AlterModelOptions(
            name='representationtoken',
            options={'ordering': ['created']},
        ),
    ]
