# Generated by Django 3.2.12 on 2023-01-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0049_auto_20230111_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
