# Generated by Django 3.2.12 on 2023-02-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kas", "0050_delete_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalsettlement",
            name="due_date_used",
            field=models.DateField(null=True),
        ),
    ]
