# Generated by Django 5.2.6 on 2025-09-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kas", "0051_finalsettlement_due_date_used"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalnote",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical note",
                "verbose_name_plural": "historical notes",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalperson",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person",
                "verbose_name_plural": "historical persons",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpersontaxyear",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person tax year",
                "verbose_name_plural": "historical person tax years",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpolicytaxyear",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical policy tax year",
                "verbose_name_plural": "historical policy tax years",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpreviousyearnegativepayout",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical previous year negative payout",
                "verbose_name_plural": "historical previous year negative payouts",
            },
        ),
        migrations.AlterField(
            model_name="historicalnote",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpersontaxyear",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpolicytaxyear",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpreviousyearnegativepayout",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
