# Generated by Django 5.2.15 on 2026-06-19 07:56

import django.db.models.deletion
import kas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0052_alter_historicalnote_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPensionCompanySummaryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=kas.models.totalpensioncompanysummaryfile_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kas.taxyear')),
            ],
            options={
                'ordering': ['tax_year'],
            },
        ),
        migrations.CreateModel(
            name='TotalPensionCompanySummaryFileDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_to', models.GenericIPAddressField(null=True)),
                ('downloaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kas.totalpensioncompanysummaryfile')),
            ],
            options={
                'ordering': ['downloaded_at'],
            },
        ),
    ]
