FROM python:3.10
ENV SUPERCRONIC_URL=https://github.com/aptible/supercronic/releases/download/v0.1.12/supercronic-linux-amd64 \
    SUPERCRONIC=supercronic-linux-amd64 \
    SUPERCRONIC_SHA1SUM=048b95b48b708983effb2e5c935a1ef8483d9e3e\
    PYTHONUNBUFFERED=1
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN mkdir /app && mkdir -p /var/cache/kas && \
    #gid/uid from salt
    groupadd -g 75050 -r kas && \
    groupadd -g 75100 -r certificate_exporter && \
    useradd -u 75050 --no-log-init -r -g kas -G certificate_exporter kas && \
    chown kas:kas /var/cache/kas && chmod a+w /var/cache/kas

# hadolint ignore=DL3008
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list' && \
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        python3-distutils gettext libxmlsec1-dev xmlsec1 postgresql-client-common postgresql-client-16 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# supercronic
RUN curl -fsSLO "$SUPERCRONIC_URL" && \
    echo "${SUPERCRONIC_SHA1SUM}  ${SUPERCRONIC}" | sha1sum -c - && \
    chmod +x "$SUPERCRONIC" && \
    mv "$SUPERCRONIC" "/usr/local/bin/${SUPERCRONIC}" && \
    ln -s "/usr/local/bin/${SUPERCRONIC}" /usr/local/bin/supercronic

ARG COMMIT_TAG
ENV COMMIT_TAG=${COMMIT_TAG:-HEAD}

COPY selvbetjening/requirements.txt /app/requirements.txt
COPY selvbetjening/.coveragerc /app/.coveragerc
RUN pip install --no-cache-dir -r /app/requirements.txt&& \
    rm /app/requirements.txt

ENV PYTHONUNBUFFERED=1
USER kas
COPY ./docker/crontab.selvbetjening /crontab
COPY ./docker/selvbetjening_entrypoint.sh /entrypoint.sh
COPY ./selvbetjening /app
EXPOSE 8000
WORKDIR /app
VOLUME  /var/cache/kas
ENTRYPOINT ["/entrypoint.sh"]
CMD ["gunicorn","-b","0.0.0.0:8000","project.wsgi:application","-w 4","--timeout 60","--error-logfile", "-","--capture-output"]
