FROM python:3.8
RUN mkdir /app
COPY selvbetjening/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
ENV PYTHONUNBUFFERED=1
#RUN useradd -r --no-create-home --uid 2000 kas #TODO find a global unique UID in salt
# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y --no-install-recommends \
python3-distutils gettext \
&& apt-get clean && rm -rf /var/lib/apt/lists/*
#USER selvbetjening
COPY ./selvbetjening /app
EXPOSE 8000
WORKDIR /app
CMD ["gunicorn","-b","0.0.0.0:8000","project.wsgi:application","-w 4","--error-logfile", "-","--capture-output"]
