FROM python:3.8
RUN mkdir /app &&\
#gid/uid from salt
groupadd -g 75050 -r kas &&\
useradd -u 75050 --no-log-init -r -g kas kas
COPY selvbetjening/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
ENV PYTHONUNBUFFERED=1
# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y --no-install-recommends \
python3-distutils gettext \
&& apt-get clean && rm -rf /var/lib/apt/lists/*
USER kas
COPY ./docker/selvbetjening_entrypoint.sh /entrypoint.sh
COPY ./selvbetjening /app
EXPOSE 8000
WORKDIR /app
ENTRYPOINT ["/entrypoint.sh"]
CMD ["gunicorn","-b","0.0.0.0:8000","project.wsgi:application","-w 4","--error-logfile", "-","--capture-output"]
