# Generated by Django 2.2.18 on 2021-03-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockR75Idx4500230',
            fields=[
                ('pt_census_guid', models.UUIDField()),
                ('tax_year', models.IntegerField()),
                ('cpr', models.TextField()),
                ('r75_ctl_sekvens_guid', models.UUIDField(primary_key=True, serialize=False)),
                ('r75_ctl_indeks_guid', models.UUIDField()),
                ('idx_nr', models.IntegerField()),
                ('res', models.TextField(blank=True, null=True)),
                ('ktd', models.TextField(blank=True, null=True)),
                ('ktt', models.TextField(blank=True, null=True)),
                ('kontotype', models.TextField(blank=True, null=True)),
                ('ibn', models.TextField(blank=True, null=True)),
                ('esk', models.TextField(blank=True, null=True)),
                ('ejerstatuskode', models.TextField(blank=True, null=True)),
                ('indestående', models.TextField(blank=True, null=True)),
                ('renteindtægt', models.TextField(blank=True, null=True)),
                ('r75_dato', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='historicalimportedr75privatepension',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='ImportedR75PrivatePension',
        ),
        migrations.DeleteModel(
            name='MockR75PrivatePension',
        ),
        migrations.DeleteModel(
            name='R75PrivatePension',
        ),
        migrations.DeleteModel(
            name='HistoricalImportedR75PrivatePension',
        ),
    ]
