# Generated by Django 2.2.18 on 2021-03-23 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eskat', '0002_auto_20210323_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='R75Idx4500230',
            fields=[
                ('pt_census_guid', models.UUIDField()),
                ('tax_year', models.IntegerField()),
                ('cpr', models.TextField()),
                ('r75_ctl_sekvens_guid', models.UUIDField(primary_key=True, serialize=False)),
                ('r75_ctl_indeks_guid', models.UUIDField()),
                ('idx_nr', models.IntegerField()),
                ('res', models.TextField(blank=True, null=True)),
                ('ktd', models.TextField(blank=True, null=True)),
                ('ktt', models.TextField(blank=True, null=True)),
                ('kontotype', models.TextField(blank=True, null=True)),
                ('ibn', models.TextField(blank=True, null=True)),
                ('esk', models.TextField(blank=True, null=True)),
                ('ejerstatuskode', models.TextField(blank=True, null=True)),
                ('indestående', models.TextField(blank=True, null=True)),
                ('renteindtægt', models.TextField(blank=True, null=True)),
                ('r75_dato', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'r75_idx_4500230',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImportedR75PrivatePension',
            fields=[
                ('pt_census_guid', models.UUIDField()),
                ('tax_year', models.IntegerField()),
                ('cpr', models.TextField()),
                ('r75_ctl_sekvens_guid', models.UUIDField(primary_key=True, serialize=False)),
                ('r75_ctl_indeks_guid', models.UUIDField()),
                ('idx_nr', models.IntegerField()),
                ('res', models.TextField(blank=True, null=True)),
                ('ktd', models.TextField(blank=True, null=True)),
                ('ktt', models.TextField(blank=True, null=True)),
                ('kontotype', models.TextField(blank=True, null=True)),
                ('ibn', models.TextField(blank=True, null=True)),
                ('esk', models.TextField(blank=True, null=True)),
                ('ejerstatuskode', models.TextField(blank=True, null=True)),
                ('indestående', models.TextField(blank=True, null=True)),
                ('renteindtægt', models.TextField(blank=True, null=True)),
                ('r75_dato', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalImportedR75PrivatePension',
            fields=[
                ('pt_census_guid', models.UUIDField()),
                ('tax_year', models.IntegerField()),
                ('cpr', models.TextField()),
                ('r75_ctl_sekvens_guid', models.UUIDField(db_index=True)),
                ('r75_ctl_indeks_guid', models.UUIDField()),
                ('idx_nr', models.IntegerField()),
                ('res', models.TextField(blank=True, null=True)),
                ('ktd', models.TextField(blank=True, null=True)),
                ('ktt', models.TextField(blank=True, null=True)),
                ('kontotype', models.TextField(blank=True, null=True)),
                ('ibn', models.TextField(blank=True, null=True)),
                ('esk', models.TextField(blank=True, null=True)),
                ('ejerstatuskode', models.TextField(blank=True, null=True)),
                ('indestående', models.TextField(blank=True, null=True)),
                ('renteindtægt', models.TextField(blank=True, null=True)),
                ('r75_dato', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical imported r75 private pension',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
