# Generated by Django 2.2.18 on 2021-03-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskat', '0003_historicalimportedr75privatepension_importedr75privatepension_r75idx4500230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalimportedr75privatepension',
            old_name='indestående',
            new_name='indestaaende',
        ),
        migrations.RenameField(
            model_name='historicalimportedr75privatepension',
            old_name='renteindtægt',
            new_name='renteindtaegt',
        ),
        migrations.RenameField(
            model_name='importedr75privatepension',
            old_name='indestående',
            new_name='indestaaende',
        ),
        migrations.RenameField(
            model_name='importedr75privatepension',
            old_name='renteindtægt',
            new_name='renteindtaegt',
        ),
        migrations.RenameField(
            model_name='mockr75idx4500230',
            old_name='indestående',
            new_name='indestaaende',
        ),
        migrations.RenameField(
            model_name='mockr75idx4500230',
            old_name='renteindtægt',
            new_name='renteindtaegt',
        ),
        migrations.AlterField(
            model_name='historicalimportedr75privatepension',
            name='indestaaende',
            field=models.TextField(blank=True, db_column='indestående', null=True),
        ),
        migrations.AlterField(
            model_name='historicalimportedr75privatepension',
            name='renteindtaegt',
            field=models.TextField(blank=True, db_column='renteindtægt', null=True),
        ),
        migrations.AlterField(
            model_name='importedr75privatepension',
            name='indestaaende',
            field=models.TextField(blank=True, db_column='indestående', null=True),
        ),
        migrations.AlterField(
            model_name='importedr75privatepension',
            name='renteindtaegt',
            field=models.TextField(blank=True, db_column='renteindtægt', null=True),
        ),
        migrations.AlterField(
            model_name='mockr75idx4500230',
            name='indestaaende',
            field=models.TextField(blank=True, db_column='indestående', null=True),
        ),
        migrations.AlterField(
            model_name='mockr75idx4500230',
            name='renteindtaegt',
            field=models.TextField(blank=True, db_column='renteindtægt', null=True),
        ),
    ]
