# Generated by Django 3.2.12 on 2022-06-13 08:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eskat", "0004_auto_20220628_1313"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalimportedkasberegningerx",
            name="capital_return_tax",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="importedkasberegningerx",
            name="capital_return_tax",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddIndex(
            model_name="importedkasberegningerx",
            index=models.Index(
                fields=["cpr", "skatteaar"], name="eskat_impor_cpr_516d15_idx"
            ),
        ),
    ]
