# Generated by Django 3.2.12 on 2022-06-13 09:13

from django.db import migrations, models
import django.db.models.deletion


def populate_person_tax_year(apps, schema_editor):
    PersonTaxYear = apps.get_model("kas", "PersonTaxYear")
    ImportedKasBeregningerX = apps.get_model("eskat", "ImportedKasBeregningerX")
    HistoricalImportedKasBeregningerX = apps.get_model(
        "eskat", "HistoricalImportedKasBeregningerX"
    )
    for item in ImportedKasBeregningerX.objects.all():
        item.person_tax_year = PersonTaxYear.objects.get(
            person__cpr=item.cpr, tax_year__year=item.skatteaar
        )
        item.save()
    for item in HistoricalImportedKasBeregningerX.objects.all():
        item.person_tax_year = PersonTaxYear.objects.get(
            person__cpr=item.cpr, tax_year__year=item.skatteaar
        )
        item.save()


def unpopulate_person_tax_year(apps, schema_editor):
    ImportedKasBeregningerX = apps.get_model("eskat", "ImportedKasBeregningerX")
    HistoricalImportedKasBeregningerX = apps.get_model(
        "eskat", "HistoricalImportedKasBeregningerX"
    )
    ImportedKasBeregningerX.objects.all().update(person_tax_year=None)
    HistoricalImportedKasBeregningerX.objects.all().update(person_tax_year=None)


class Migration(migrations.Migration):

    dependencies = [
        ("kas", "0041_alter_finalsettlement_pseudo_amount"),
        ("eskat", "0005_auto_20220613_1017"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalimportedkasberegningerx",
            name="person_tax_year",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="kas.persontaxyear",
            ),
        ),
        migrations.AddField(
            model_name="importedkasberegningerx",
            name="person_tax_year",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kas.persontaxyear",
            ),
        ),
        migrations.RunPython(
            populate_person_tax_year, reverse_code=unpopulate_person_tax_year
        ),
        migrations.AlterField(
            model_name="historicalimportedkasberegningerx",
            name="person_tax_year",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="kas.persontaxyear",
            ),
        ),
        migrations.AlterField(
            model_name="importedkasberegningerx",
            name="person_tax_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kas.persontaxyear"
            ),
        ),
    ]
