# Generated by Django 3.2.12 on 2023-01-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eskat', '0009_alter_importedkasberegningerx_person_tax_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importedkasberegningerx',
            options={'ordering': ['skatteaar', 'cpr']},
        ),
        migrations.AlterModelOptions(
            name='importedkasmandtal',
            options={'ordering': ['skatteaar', 'cpr']},
        ),
        migrations.AlterModelOptions(
            name='importedr75privatepension',
            options={'ordering': ['tax_year', 'cpr']},
        ),
        migrations.AlterModelOptions(
            name='kasberegningerx',
            options={'managed': False, 'ordering': ['skatteaar', 'cpr', 'bank_reg_nr']},
        ),
        migrations.AlterModelOptions(
            name='mockkasberegningerx',
            options={'ordering': ['skatteaar', 'cpr']},
        ),
        migrations.AlterModelOptions(
            name='mockkasmandtal',
            options={'ordering': ['skatteaar', 'cpr']},
        ),
        migrations.AlterModelOptions(
            name='mockr75idx4500230',
            options={'ordering': ['tax_year', 'cpr']},
        ),
        migrations.AlterModelOptions(
            name='r75spreadsheetfile',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='r75spreadsheetimport',
            options={'ordering': ['tax_year', 'cpr']},
        ),
    ]
