# Generated by Django 5.2.6 on 2025-09-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eskat", "0010_auto_20230105_1019"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalimportedkasberegningerx",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical imported kas beregninger x",
                "verbose_name_plural": "historical imported kas beregninger xs",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalimportedkasmandtal",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical imported kas mandtal",
                "verbose_name_plural": "historical imported kas mandtals",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalimportedr75privatepension",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical imported r75 private pension",
                "verbose_name_plural": "historical imported r75 private pensions",
            },
        ),
        migrations.AlterField(
            model_name="historicalimportedkasberegningerx",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalimportedkasmandtal",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalimportedr75privatepension",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
