# Generated by Django 2.2.18 on 2021-03-23 18:12

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pretty_title', models.CharField(blank=True, max_length=255, null=True)),
                ('arguments', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('job_type', models.TextField(choices=[('ImportMandtalJob', 'Import af mandtal'), ('ImportR75Job', 'Import af data fra R75'), ('GenerateReportsForYear', 'Generere KAS selvangivelser'), ('DispatchTaxYear', 'Afsendelse af KAS selvangivelser for et givent år'), ('ImportEskatMockup', 'Import af mockup data for eSkat'), ('ClearTestData', 'Nulstil test-data'), ('ResetToMockupOnly', 'Nulstil til KUN mockup data'), ('ImportAllMockupMandtal', 'Imporer alle mockup mandtal'), ('ImportAllMockupR75', 'Imporer alle mockup r75')])),
                ('rq_job_id', models.TextField(blank=True, null=True)),
                ('checkpoint', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('progress', models.IntegerField(blank=True, default=0)),
                ('status', models.TextField(blank=True, choices=[('queued', 'Sat i kø'), ('started', 'Igang'), ('deferred', 'Afventer'), ('failed', 'Fejlet'), ('finished', 'Færdig')], default='queued')),
                ('traceback', models.TextField(blank=True, default='')),
                ('queue', models.TextField(blank=True, default='')),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worker.Job')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
