# Generated by Django 2.2.18 on 2021-03-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.TextField(blank=True, choices=[('queued', 'Sat i kø'), ('started', 'Igang'), ('deferred', 'Afventer'), ('failed', 'Fejlet'), ('finished', 'Færdig')], default='queued'),
        ),
    ]
