# Generated by Django 2.2.18 on 2021-02-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.TextField(choices=[('slow_job', 'Slow job'), ('slow_job_with_children', 'Job with children')]),
        ),
    ]
