# Generated by Django 2.2.18 on 2021-02-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20210203_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.TextField(choices=[('slow_job', 'Slow job'), ('slow_job_with_children', 'Job with children'), ('job_with_exception', 'Job with exception')]),
        ),
    ]
