# Generated by Django 2.2.18 on 2021-03-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_auto_20210308_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.TextField(choices=[('ImportMandtalJob', 'Import af mandtal'), ('ImportR75Job', 'Import af data fra R75'), ('DispatchTaxYear', 'Afsendelse af Kas opgørelse for et given år')]),
        ),
    ]
