# Generated by Django 2.2.18 on 2021-03-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_auto_20210315_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pretty_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.TextField(choices=[('ImportMandtalJob', 'Import af mandtal'), ('ImportR75Job', 'Import af data fra R75'), ('DispatchTaxYear', 'Afsendelse af Kas opgørelse for et given år'), ('ImportEskatMockup', 'Import af mockup data for eSkat'), ('ClearTestData', 'Nulstil test-data')]),
        ),
    ]
