# Generated by Django 2.2.18 on 2021-09-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_auto_20210806_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.TextField(choices=[('Autoligning', 'Kør autoligning'), ('ImportPrePaymentFile', 'Import af forudindbetalinger'), ('ImportMandtalJob', 'Import af mandtal'), ('ImportR75Job', 'Import af data fra R75'), ('ForceFinalize', 'Forcering af slutligning på alle udestående policer'), ('GenerateReportsForYear', 'Generering af KAS selvangivelser for et givet år'), ('DispatchTaxYear', 'Afsendelse af KAS selvangivelser for et givet år'), ('GenerateFinalSettlements', 'Generering af KAS slutopgørelser for et givet år'), ('GenerateBatchAndTransactions', 'Generering af Transaktioner og batch for et givent år'), ('DispatchFinalSettlements', 'Afsendelse af KAS slutopgørelser for et givet år'), ('ImportEskatMockup', 'Import af mockup data for eSkat'), ('ClearTestData', 'Nulstil test-data'), ('ResetToMockupOnly', 'Nulstil til KUN mockup data'), ('ImportAllMockupMandtal', 'Importer alle mockup mandtal'), ('ImportAllMockupR75', 'Importer alle mockup r75'), ('SendBatch', 'Sender et Q10 batch')]),
        ),
    ]
